# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Trip' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

  pod 'PXGoogleDirections'
  pod 'SwiftLocation'
  use_frameworks!

  # Pods for Trip


end
